### PR TITLE
paging logic

### PR DESCRIPTION
**Pull request by lior-gershony**
the purpose of this PR is to add some paging logic that will accumulate the results for all pages.
this new service will be called from the controller (or maybe another service), and the controller will return a response containing the accumulated results from all pages.

In the future we'd like to:
 1. Make `CampaignWrapperRO` generic - so we'll be able to parse any type of entity structure within any FB response
 2. Pass a function to perform the REST call, instead of using a specific facade call within `FacebookDataFetchingService` 

SOCIAL-36388

### CODE REVIEW

**Comment by lior-gershony** [comment]
@morantavori can you please take a look?

**Comment by morantavori** [comment]
@lior-gershony mind adding the compromises we're making to the PR description? Something to make out offline conversations documented. Something like - 
In the future we'd like to - 
 1. Make `CampaignWrapperRO` generic...
 2. Pass a function instead of a specific call to the service...

**Comment by lior-gershony** [comment]
@morantavori sure - edited the PR's description.

**Comment by morantavori** [comment]
> @morantavori sure - edited the PR's description.

OK I edited it a bit to include a bit more context :innocent:

**Comment by lior-gershony** [comment]
@morantavori thanks for the review!
fixed the comments and conflicts.

**Pull request merged**
