### PR TITLE
remove all mysql stuff

### PR DESCRIPTION
**Pull request by lior-gershony**
currently, we don't need mysql in this service - so we had to remove some code in that area.
@talhasson thanks a lot for the help!

### CODE REVIEW

**Comment by lior-gershony** [comment]
@talhasson @mosheeshel can you please approve?

**Comment by lior-gershony** [comment]
retest this please

**Comment by lior-gershony** [comment]
BTW, the [pull-request job](https://jenkins.kenshoo-lab.com/job/facebook-gateway-pull-request/) is not triggered - and I don't have settings permissions for this repo. maybe we need to integrate this repo with the jenkins jobs?
@kenshoo/devenablement

**Comment by talhasson** [comment]
retest this please

**Comment by talhasson** [comment]
@lior-gershony @kenshoo/devenablement 
We added the hubot webhook (for release) but forgot to add the Jenkins webhook (for PRs), so I added it now and it now works

**Comment by mosheeshel** [comment]
שועל! 
I was just adding, and you got there a second first !

**Comment by talhasson** [comment]
:)

**Pull request merged**
